services:
  market-db:
    container_name: market-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: marketadmin
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: marketdb
    volumes:
      - ../market-app/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ../market-app/src/main/resources/seed-dev.sql:/docker-entrypoint-initdb.d/02_seed-dev.sql
      - ../payment-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/03_payment_schema.sql
      - market-data:/var/lib/postgresql/data

  payment-service:
    container_name: payment-service
    build:
      context: ..
      dockerfile: payment-service/Dockerfile
    restart: on-failure
    environment:
      POSTGRES_USER: marketadmin
      POSTGRES_PASSWORD: testpassword
      DB_HOST: market-db
      DB_PORT: 5432
      DB_NAME: marketdb
      KEYCLOAK_URL: http://keycloak:8080
    depends_on:
      - market-db

  redis:
    image: redis:7-alpine

  market-app:
    container_name: market-app
    build:
      context: ..
      dockerfile: market-app/Dockerfile
    restart: on-failure
    environment:
      POSTGRES_USER: marketadmin
      POSTGRES_PASSWORD: testpassword
      DB_HOST: market-db
      DB_PORT: 5432
      DB_NAME: marketdb
      PAYMENT_SERVICE_URL: http://payment-service:8081/api/v1
      REDIS_HOST: redis
      KEYCLOAK_URL: http://keycloak:8080
    depends_on:
      - market-db
      - payment-service
      - redis

  gw:
    container_name: gw
    image: nginx:1.29.0-alpine-perl
    ports:
      - "80:80"
    volumes:
      - ../proxy/nginx-market-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - market-app

volumes:
  market-data:
